#!/bin/bash
# Nightly backup of the `camp` Postgres database (Build Brief v2.1 Part 3).
#
# This formalizes what an ad hoc host script (camp-backup.sh, outside this
# repo) was already doing nightly since 2026-08-28 — local pg_dump, gzip, an
# off-box copy via rclone to Dropbox ("Sychar CMMS Backup" folder), logged to
# /root/backups/backup.log. The two real changes from that script are custom
# (-Fc) dump format instead of plain SQL, and 30-day retention instead of 14.
# Dropbox stays the off-box target rather than switching to a second
# DigitalOcean Spaces bucket: it's a fully separate provider from the one
# that already holds attachments (SPACES_*), which isolates credentials at
# least as well as a second bucket under the same DO account would — the
# brief's "a credential compromise or fat-fingered bucket delete should not
# take both" concern is already satisfied.
#
# Spaces attachments (the photos themselves) are NOT covered by this script —
# see the runbook. That's a deliberate scope boundary, not an oversight:
# Spaces has its own durability, and losing a photo (re-photograph the
# building) is a different order of loss than losing condition observations
# that can only be regenerated by physically re-walking 337 buildings.
#
# Credentials: none hardcoded here. pg_dump runs inside the nocodb-db
# container via `docker exec`, authenticating as camp_app over the
# container's local socket (same trust-auth path the app's own migrations
# already use) — no password needs to cross this script at all. The Dropbox
# side authenticates via rclone's own stored token (`rclone config`), set up
# once outside of this script and outside of git.
set -euo pipefail

BACKUP_DIR="${BACKUP_DIR:-$HOME/backups}"
LOG_FILE="${BACKUP_LOG_FILE:-$BACKUP_DIR/backup.log}"
RETENTION_DAYS=30
DB_CONTAINER="${DB_CONTAINER:-nocodb-db}"
DB_USER="${DB_USER:-camp_app}"
DB_NAME="${DB_NAME:-camp}"
RCLONE_REMOTE="${RCLONE_REMOTE:-dropbox:Sychar CMMS Backup}"

mkdir -p "$BACKUP_DIR"
STAMP=$(date +%Y-%m-%d-%H%M)
FILE="$BACKUP_DIR/sychar-$STAMP.dump.gz"

log() { echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') $1" | tee -a "$LOG_FILE"; }

# Custom format (-Fc), not plain SQL: lets a restore target one table with
# pg_restore instead of always replaying the whole dump, and supports
# parallel restore (-j) once this database is too big for that not to
# matter. gzip on top is redundant with -Fc's own internal compression but
# matches the filename convention (sychar-YYYY-MM-DD-HHMM.dump.gz) the brief
# specifies, and costs nothing meaningful at this database's current size.
if docker exec "$DB_CONTAINER" pg_dump -U "$DB_USER" -d "$DB_NAME" -Fc | gzip > "$FILE"; then
  log "OK backup written to $FILE ($(du -h "$FILE" | cut -f1))"
else
  log "FAILED pg_dump/gzip for $FILE"
  rm -f "$FILE"
  exit 1
fi

# Local retention. Also sweeps camp_*.sql.gz — the old ad hoc script's naming
# — on the same window, so those don't just sit there unmanaged forever now
# that the script that used to clean them up is gone.
find "$BACKUP_DIR" -maxdepth 1 \( -name 'sychar-*.dump.gz' -o -name 'camp_*.sql.gz' \) -mtime "+$RETENTION_DAYS" -print -delete \
  | while IFS= read -r f; do log "deleted local backup older than ${RETENTION_DAYS}d: $f"; done

# Off-box copy is best-effort in the sense that a missing rclone config must
# never block the local backup above (which has already succeeded by this
# point) — but a FAILED upload (remote configured, copy itself errored) still
# fails this script, because a silently-broken off-box copy is worse than a
# loud one: nothing else will ever notice a Dropbox token that's quietly
# stopped working.
if command -v rclone >/dev/null 2>&1 && rclone listremotes 2>/dev/null | grep -q '^dropbox:'; then
  if rclone copy "$FILE" "$RCLONE_REMOTE/"; then
    log "OK copied to Dropbox: $RCLONE_REMOTE/$(basename "$FILE")"
  else
    log "FAILED Dropbox upload for $FILE — local copy is still safe, but the off-box copy is missing until this is fixed"
    exit 1
  fi
  rclone delete --min-age "${RETENTION_DAYS}d" "$RCLONE_REMOTE/" 2>&1 | tee -a "$LOG_FILE" || true
else
  log "WARNING skipping off-box copy — rclone 'dropbox' remote not configured on this host"
fi
