// Renders report data (from reportData.js) into HTML and plain text. Kept
// separate from data-building so "what a report contains" and "how it looks" can
// change independently. HTML uses inline styles only — email clients and the
// print stylesheet both need that, not an external stylesheet.

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

const KIND_LABEL = { component: 'Component Event', finding: 'Condition Finding', workorder: 'Work Order' };
const fmtDate = (iso) => (iso || '').slice(0, 10);
const fmtDateTime = (iso) => (iso || '').slice(0, 16);
const fmtMoney = (n) => (n == null ? '—' : `$${Number(n).toLocaleString()}`);

function htmlShell(title, subtitle, bodyHtml) {
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title></head>
<body style="margin:0;padding:24px;background:#f6f7fb;font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#1a1d29;">
  <div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e5e7f0;border-radius:16px;padding:28px;">
    <h1 style="margin:0 0 4px;font-size:1.4rem;">🏕️ ${escapeHtml(title)}</h1>
    <div style="color:#6b7086;font-size:0.9rem;margin-bottom:20px;">${escapeHtml(subtitle)}</div>
    ${bodyHtml}
    <div style="margin-top:28px;padding-top:14px;border-top:1px solid #e5e7f0;color:#9298b0;font-size:0.78rem;">
      Generated by Camp Sychar Audit — ${escapeHtml(new Date().toISOString().slice(0, 16).replace('T', ' '))}
    </div>
  </div>
</body></html>`;
}

function entryRowHtml(e) {
  return `
    <tr>
      <td style="padding:8px 10px;border-bottom:1px solid #eef0f6;font-size:0.85rem;color:#6b7086;white-space:nowrap;vertical-align:top;">${escapeHtml(fmtDateTime(e.at))}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #eef0f6;vertical-align:top;">
        <strong>${escapeHtml(KIND_LABEL[e.kind] || e.kind)}:</strong> ${escapeHtml(e.title)}<br/>
        <span style="color:#6b7086;font-size:0.85rem;">${escapeHtml(e.assetName || '')}${e.assetName && e.detail ? ' · ' : ''}${escapeHtml(e.detail || '')}</span>
        ${e.notes ? `<div style="color:#6b7086;font-size:0.82rem;margin-top:2px;">${escapeHtml(e.notes)}</div>` : ''}
      </td>
    </tr>`;
}

export function renderActivityHtml({ entries, from, to, detailed }) {
  const subtitle = `${from ? `From ${from}` : 'All time'}${to ? ` to ${to}` : ''} · ${entries.length} item${entries.length === 1 ? '' : 's'}`;
  if (!detailed) {
    const counts = entries.reduce((acc, e) => { acc[e.kind] = (acc[e.kind] || 0) + 1; return acc; }, {});
    const countsHtml = Object.entries(counts).map(([kind, n]) => `
      <div style="display:inline-block;background:#f0f2fb;border-radius:12px;padding:10px 16px;margin:0 8px 8px 0;">
        <div style="font-size:1.3rem;font-weight:800;">${n}</div>
        <div style="font-size:0.78rem;color:#6b7086;text-transform:uppercase;letter-spacing:0.04em;">${escapeHtml(KIND_LABEL[kind] || kind)}${n === 1 ? '' : 's'}</div>
      </div>`).join('');
    const highlights = entries.slice(0, 12).map((e) => `
      <li style="margin-bottom:6px;"><strong>${escapeHtml(fmtDate(e.at))}</strong> — ${escapeHtml(KIND_LABEL[e.kind] || e.kind)}: ${escapeHtml(e.title)}${e.assetName ? ` (${escapeHtml(e.assetName)})` : ''}</li>`).join('');
    return htmlShell('Activity Summary', subtitle, `
      <div>${countsHtml}</div>
      <h3 style="margin:20px 0 8px;font-size:1rem;">Highlights</h3>
      <ul style="padding-left:20px;margin:0;">${highlights || '<li>No activity in this range.</li>'}</ul>
    `);
  }
  return htmlShell('Detailed Activity Log', subtitle, `
    <table style="width:100%;border-collapse:collapse;">
      ${entries.map(entryRowHtml).join('') || '<tr><td style="padding:14px;color:#6b7086;">No activity in this range.</td></tr>'}
    </table>
  `);
}

export function renderActivityText({ entries, from, to, detailed }) {
  const lines = [];
  lines.push(`CAMP SYCHAR — ${detailed ? 'DETAILED ACTIVITY LOG' : 'ACTIVITY SUMMARY'}`);
  lines.push(`${from ? `From ${from}` : 'All time'}${to ? ` to ${to}` : ''} — ${entries.length} item(s)`);
  lines.push('');
  if (!detailed) {
    const counts = entries.reduce((acc, e) => { acc[e.kind] = (acc[e.kind] || 0) + 1; return acc; }, {});
    Object.entries(counts).forEach(([kind, n]) => lines.push(`${KIND_LABEL[kind] || kind}s: ${n}`));
    lines.push('', 'Highlights:');
    entries.slice(0, 12).forEach((e) => lines.push(`- ${fmtDate(e.at)}  ${KIND_LABEL[e.kind] || e.kind}: ${e.title}${e.assetName ? ` (${e.assetName})` : ''}`));
  } else {
    entries.forEach((e) => {
      lines.push(`${fmtDateTime(e.at)}  [${KIND_LABEL[e.kind] || e.kind}] ${e.title}`);
      const meta = [e.assetName, e.detail].filter(Boolean).join(' · ');
      if (meta) lines.push(`  ${meta}`);
      if (e.notes) lines.push(`  ${e.notes}`);
    });
    if (!entries.length) lines.push('No activity in this range.');
  }
  return lines.join('\n');
}

export function renderCapitalHtml({ rows, summary }) {
  const summaryHtml = summary.map((s) => `
    <div style="display:inline-block;background:#f0f2fb;border-radius:12px;padding:10px 16px;margin:0 8px 8px 0;">
      <div style="font-size:1.1rem;font-weight:800;">${s.count}</div>
      <div style="font-size:0.78rem;color:#6b7086;">${escapeHtml(s.bucket)}${s.totalCost ? ` · ${fmtMoney(s.totalCost)}` : ''}</div>
    </div>`).join('');
  const rowsHtml = rows.map((r) => `
    <tr>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(r.assetName)}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(r.componentType)}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(r.condition || '—')}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${r.estReplacementYear || '—'}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${fmtMoney(r.estReplacementCost)}</td>
    </tr>`).join('');
  return htmlShell('Capital Plan', `Current component state, soonest replacement first · ${rows.length} component(s)`, `
    <div>${summaryHtml}</div>
    <table style="width:100%;border-collapse:collapse;margin-top:14px;">
      <tr style="text-align:left;font-size:0.78rem;color:#6b7086;text-transform:uppercase;">
        <th style="padding:7px 10px;">Asset</th><th>Component</th><th>Condition</th><th>Est. Year</th><th>Est. Cost</th>
      </tr>
      ${rowsHtml || '<tr><td style="padding:14px;color:#6b7086;">No component data yet.</td></tr>'}
    </table>
  `);
}

export function renderCapitalText({ rows, summary }) {
  const lines = ['CAMP SYCHAR — CAPITAL PLAN', `Current component state, soonest replacement first — ${rows.length} component(s)`, ''];
  summary.forEach((s) => lines.push(`${s.bucket}: ${s.count} component(s)${s.totalCost ? `, ${fmtMoney(s.totalCost)}` : ''}`));
  lines.push('', 'Asset | Component | Condition | Est. Year | Est. Cost');
  rows.forEach((r) => lines.push(`${r.assetName} | ${r.componentType} | ${r.condition || '—'} | ${r.estReplacementYear || '—'} | ${fmtMoney(r.estReplacementCost)}`));
  if (!rows.length) lines.push('No component data yet.');
  return lines.join('\n');
}
