// Renders report data (from reportData.js) into HTML and plain text. Kept
// separate from data-building so "what a report contains" and "how it looks" can
// change independently. HTML uses inline styles only — email clients and the
// print stylesheet both need that, not an external stylesheet.

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

// Report data may carry either ISO date strings or raw `pg` driver Date
// objects straight from `date`/`timestamp` columns — normalize both to a
// string before slicing.
const isoStr = (v) => (v instanceof Date ? v.toISOString() : String(v || ''));
const fmtDate = (iso) => isoStr(iso).slice(0, 10);
const fmtMoney = (n) => (n == null ? '—' : `$${Number(n).toLocaleString()}`);

export function htmlShell(title, subtitle, bodyHtml) {
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title></head>
<body style="margin:0;padding:24px;background:#f6f7fb;font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#1a1d29;">
  <div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e5e7f0;border-radius:16px;padding:28px;">
    <h1 style="margin:0 0 4px;font-size:1.4rem;">🏕️ ${escapeHtml(title)}</h1>
    <div style="color:#6b7086;font-size:0.9rem;margin-bottom:20px;">${escapeHtml(subtitle)}</div>
    ${bodyHtml}
    <div style="margin-top:28px;padding-top:14px;border-top:1px solid #e5e7f0;color:#9298b0;font-size:0.78rem;">
      Generated by Sychar Operations — ${escapeHtml(new Date().toISOString().slice(0, 16).replace('T', ' '))}
    </div>
  </div>
</body></html>`;
}

function countPillsHtml(items, key) {
  return items.map((s) => `
    <div style="display:inline-block;background:#f0f2fb;border-radius:12px;padding:10px 16px;margin:0 8px 8px 0;">
      <div style="font-size:1.1rem;font-weight:800;">${s.count}</div>
      <div style="font-size:0.78rem;color:#6b7086;">${escapeHtml(s[key])}</div>
    </div>`).join('');
}

function boardListRowsHtml(items) {
  return items.map((i) => `
    <tr>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;white-space:nowrap;">${escapeHtml(fmtDate(i.scheduledDate || i.dateCompleted))}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(i.title)}${i.jobLineTitle ? ` — ${escapeHtml(i.jobLineTitle)}` : ''}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(i.assetName || '—')}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${i.priority ? escapeHtml(i.priority) : fmtMoney(i.cost)}</td>
    </tr>`).join('');
}

// Savings are the one place cents matter (a $14.99/mo subscription) — the
// report's usual fmtMoney drops trailing zeros.
const fmtMoneyCents = (n) => `$${Number(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const fmtHours = (n) => `${Math.round(Number(n) * 100) / 100}h`;

// Administrative Work section, shared by the Work Performed and Board
// reports (the latter only gets tasks flagged include_in_board_report).
function adminWorkSectionHtml(adminWork) {
  const tasks = adminWork?.tasks || [];
  return `
    <h2 style="margin:28px 0 4px;font-size:1.1rem;border-top:2px solid #eef0f6;padding-top:14px;">Administrative Work <span style="color:#6b7086;font-weight:400;font-size:0.85rem;">— ${tasks.length} task(s)${adminWork?.totalHours ? ` · ${fmtHours(adminWork.totalHours)}` : ''}</span></h2>
    ${adminWork?.savingsTaskCount ? `
      <div style="background:#eef7f0;border-left:4px solid #2e8b57;padding:8px 12px;margin:8px 0;border-radius:4px;">
        <strong>Recurring savings: ${fmtMoneyCents(adminWork.monthlySavings)}/month · ${fmtMoneyCents(adminWork.annualizedSavings)}/year</strong>
        <span style="color:#6b7086;font-size:0.85rem;"> — from ${adminWork.savingsTaskCount} task(s)</span>
      </div>` : ''}
    ${tasks.map((t) => `
      <div style="border-bottom:1px solid #eef0f6;padding:10px 0;">
        <div><strong>${escapeHtml(t.title)}</strong>${t.category ? ` <span style="color:#6b7086;font-size:0.85rem;">· ${escapeHtml(t.category)}</span>` : ''}</div>
        <div style="color:#6b7086;font-size:0.85rem;">${escapeHtml(fmtDate(t.date))} · ${escapeHtml(t.status)}${t.hours ? ` · ${fmtHours(t.hours)}` : ''}${t.recurringMonthlySavings ? ` · <span style="color:#2e8b57;">saves ${fmtMoneyCents(t.recurringMonthlySavings)}/mo</span>` : ''}</div>
        ${t.description ? `<div style="font-size:0.9rem;margin-top:2px;white-space:pre-wrap;">${escapeHtml(t.description)}</div>` : ''}
      </div>`).join('') || '<p style="color:#6b7086;margin:4px 0;">No administrative tasks in this range.</p>'}`;
}
function adminWorkSectionText(adminWork) {
  const tasks = adminWork?.tasks || [];
  const lines = [`ADMINISTRATIVE WORK — ${tasks.length} task(s)${adminWork?.totalHours ? `, ${fmtHours(adminWork.totalHours)}` : ''}`];
  if (adminWork?.savingsTaskCount) {
    lines.push(`  Recurring savings: ${fmtMoneyCents(adminWork.monthlySavings)}/month, ${fmtMoneyCents(adminWork.annualizedSavings)}/year (from ${adminWork.savingsTaskCount} task(s))`);
  }
  tasks.forEach((t) => lines.push(`  ${fmtDate(t.date)}  ${t.title}${t.category ? ` [${t.category}]` : ''} — ${t.status}${t.hours ? `, ${fmtHours(t.hours)}` : ''}${t.recurringMonthlySavings ? `, saves ${fmtMoneyCents(t.recurringMonthlySavings)}/mo` : ''}`));
  if (!tasks.length) lines.push('  No administrative tasks in this range.');
  return lines;
}

// Board / monthly report: current open-WO snapshot (status/priority/funding),
// plus what happened and what's next relative to today — regardless of the
// period bounds, which only scope the "Completed" section (a board wants to
// know what's overdue/upcoming right now, not just within the report month).
export function renderBoardReportHtml({ periodStart, periodEnd, statusCounts, priorityCounts, fundingSourceTotals, completed, upcoming, overdue, adminWork }) {
  const fundingRowsHtml = fundingSourceTotals.map((f) => `
    <tr><td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(f.label)}</td>
        <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;text-align:right;">${fmtMoney(f.total)}</td></tr>`).join('');
  const listTable = (items, emptyLabel) => `
    <table style="width:100%;border-collapse:collapse;margin-bottom:20px;">
      ${boardListRowsHtml(items) || `<tr><td style="padding:14px;color:#6b7086;">${escapeHtml(emptyLabel)}</td></tr>`}
    </table>`;
  return htmlShell('Board Report', `${periodStart} to ${periodEnd}`, `
    <h3 style="margin:0 0 8px;font-size:1rem;">Open Work Orders by Status</h3>
    <div>${countPillsHtml(statusCounts, 'status') || '<span style="color:#6b7086;">None open.</span>'}</div>
    <h3 style="margin:20px 0 8px;font-size:1rem;">By Priority</h3>
    <div>${countPillsHtml(priorityCounts, 'priority') || '<span style="color:#6b7086;">None open.</span>'}</div>
    <h3 style="margin:20px 0 8px;font-size:1rem;">Outstanding Cost by Funding Source</h3>
    <table style="width:100%;border-collapse:collapse;margin-bottom:20px;">${fundingRowsHtml || '<tr><td style="padding:14px;color:#6b7086;">No outstanding cost.</td></tr>'}</table>
    <h3 style="margin:0 0 8px;font-size:1rem;">Completed This Period (${completed.length})</h3>
    ${listTable(completed, 'Nothing completed this period.')}
    <h3 style="margin:0 0 8px;font-size:1rem;">Overdue (${overdue.length})</h3>
    ${listTable(overdue, 'Nothing overdue.')}
    <h3 style="margin:0 0 8px;font-size:1rem;">Upcoming (${upcoming.length})</h3>
    ${listTable(upcoming, 'Nothing scheduled.')}
    ${adminWorkSectionHtml(adminWork)}
  `);
}

export function renderBoardReportText({ periodStart, periodEnd, statusCounts, priorityCounts, fundingSourceTotals, completed, upcoming, overdue, adminWork }) {
  const lines = ['CAMP SYCHAR — BOARD REPORT', `${periodStart} to ${periodEnd}`, ''];
  lines.push('Open Work Orders by Status:');
  statusCounts.forEach((s) => lines.push(`  ${s.status}: ${s.count}`));
  if (!statusCounts.length) lines.push('  None open.');
  lines.push('', 'By Priority:');
  priorityCounts.forEach((p) => lines.push(`  ${p.priority}: ${p.count}`));
  if (!priorityCounts.length) lines.push('  None open.');
  lines.push('', 'Outstanding Cost by Funding Source:');
  fundingSourceTotals.forEach((f) => lines.push(`  ${f.label}: ${fmtMoney(f.total)}`));
  if (!fundingSourceTotals.length) lines.push('  None.');
  lines.push('', `Completed This Period (${completed.length}):`);
  completed.forEach((c) => lines.push(`  ${fmtDate(c.dateCompleted)}  ${c.title}${c.assetName ? ` (${c.assetName})` : ''} — ${fmtMoney(c.cost)}`));
  if (!completed.length) lines.push('  None.');
  lines.push('', `Overdue (${overdue.length}):`);
  overdue.forEach((o) => lines.push(`  ${fmtDate(o.scheduledDate)}  ${o.title}${o.jobLineTitle ? ` — ${o.jobLineTitle}` : ''}${o.assetName ? ` (${o.assetName})` : ''} [${o.priority}]`));
  if (!overdue.length) lines.push('  None.');
  lines.push('', `Upcoming (${upcoming.length}):`);
  upcoming.forEach((u) => lines.push(`  ${fmtDate(u.scheduledDate)}  ${u.title}${u.jobLineTitle ? ` — ${u.jobLineTitle}` : ''}${u.assetName ? ` (${u.assetName})` : ''} [${u.priority}]`));
  if (!upcoming.length) lines.push('  None.');
  lines.push('', ...adminWorkSectionText(adminWork));
  return lines.join('\n');
}

export function renderForwardFocusHtml({ items, total }) {
  const rowsHtml = items.map((i) => `
    <tr>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(i.kind === 'workOrder' ? 'Work Order' : 'Condition Finding')}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(i.title)}${i.jobLineTitle ? ` — ${escapeHtml(i.jobLineTitle)}` : ''}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(i.assetName || '—')}</td>
      <td style="padding:7px 10px;border-bottom:1px solid #eef0f6;">${fmtMoney(i.cost)}${i.costBasis === 'historical average' ? ' <span style="color:#6b7086;font-size:0.75rem;">(hist. avg)</span>' : ''}</td>
    </tr>`).join('');
  return htmlShell('Forward Focus', `Board-flagged items · ${items.length} item(s) · ${fmtMoney(total)} total`, `
    <table style="width:100%;border-collapse:collapse;">
      <tr style="text-align:left;font-size:0.78rem;color:#6b7086;text-transform:uppercase;">
        <th style="padding:7px 10px;">Type</th><th>Item</th><th>Asset</th><th>Est. Cost</th>
      </tr>
      ${rowsHtml || '<tr><td style="padding:14px;color:#6b7086;">Nothing flagged for the board right now.</td></tr>'}
    </table>
  `);
}

export function renderForwardFocusText({ items, total }) {
  const lines = ['CAMP SYCHAR — FORWARD FOCUS', `Board-flagged items — ${items.length} item(s), ${fmtMoney(total)} total`, ''];
  items.forEach((i) => lines.push(`${i.kind === 'workOrder' ? 'WO' : 'CF'}  ${i.title}${i.assetName ? ` (${i.assetName})` : ''} — ${fmtMoney(i.cost)}${i.costBasis === 'historical average' ? ' (hist. avg)' : ''}`));
  if (!items.length) lines.push('Nothing flagged for the board right now.');
  return lines.join('\n');
}

// "Work Performed in a Date Range" (§6.2.1) — grouped by building, images
// embed (After photos, capped per WO — see getReportImagesForJobLines),
// documents would link but this report only ever shows images by
// construction (image-kind filter is in the raw-data query).

export function renderWorkPerformedHtml({ from, to, buildings, totalLines, totalCost, totalHours, adminWork }) {
  const buildingHtml = (b) => `
    <h3 style="margin:20px 0 4px;font-size:1rem;">${escapeHtml(b.location)} <span style="color:#6b7086;font-weight:400;font-size:0.85rem;">— ${fmtMoney(b.totalCost)} · ${b.totalHours}h</span></h3>
    ${b.lines.map((l) => `
      <div style="border-bottom:1px solid #eef0f6;padding:10px 0;">
        <div><strong>${escapeHtml(l.title)}</strong> — WO ${escapeHtml(l.woNumber || l.workOrderId)}${l.assetName ? ` · ${escapeHtml(l.assetName)}` : ''}</div>
        <div style="color:#6b7086;font-size:0.85rem;">${escapeHtml(fmtDate(l.completedDate))} · ${fmtMoney(l.cost)}${l.hours ? ` · ${l.hours}h` : ''}</div>
        ${l.correction ? `<div style="font-size:0.9rem;margin-top:2px;">${escapeHtml(l.correction)}</div>` : ''}
        ${l.images.length ? `<div style="margin-top:6px;">${l.images.map((img) => `<img src="${escapeHtml(img.Url)}" alt="${escapeHtml(img.Caption || '')}" style="max-width:220px;max-height:220px;border-radius:8px;margin:0 6px 6px 0;" />`).join('')}</div>` : ''}
      </div>`).join('')}`;
  const tasks = adminWork?.tasks || [];
  const adminHtml = adminWorkSectionHtml(adminWork);
  return htmlShell('Work Performed', `${from} to ${to} · ${totalLines} line(s) · ${fmtMoney(totalCost)} · ${totalHours}h${tasks.length ? ` · ${tasks.length} admin task(s)` : ''}`, `
    ${buildings.map(buildingHtml).join('') || '<p style="color:#6b7086;">No completed work in this range.</p>'}
    ${adminHtml}
  `);
}
export function renderWorkPerformedText({ from, to, buildings, totalLines, totalCost, totalHours, adminWork }) {
  const tasks = adminWork?.tasks || [];
  const lines = ['CAMP SYCHAR — WORK PERFORMED', `${from} to ${to} — ${totalLines} line(s), ${fmtMoney(totalCost)}, ${totalHours}h${tasks.length ? `, ${tasks.length} admin task(s)` : ''}`, ''];
  buildings.forEach((b) => {
    lines.push(`${b.location} — ${fmtMoney(b.totalCost)}, ${b.totalHours}h`);
    b.lines.forEach((l) => lines.push(`  ${fmtDate(l.completedDate)}  ${l.title} (WO ${l.woNumber || l.workOrderId}${l.assetName ? `, ${l.assetName}` : ''}) — ${fmtMoney(l.cost)}`));
  });
  if (!buildings.length) lines.push('No completed work in this range.');
  lines.push('', ...adminWorkSectionText(adminWork));
  return lines.join('\n');
}

// "Deferred Maintenance Backlog" (§6.2.2) — grouped by severity, worst
// first, each group's dollar total.
export function renderDeferredBacklogHtml({ groups, totalCost, totalCount }) {
  const groupHtml = (g) => `
    <h3 style="margin:20px 0 4px;font-size:1rem;">${escapeHtml(g.severity)} <span style="color:#6b7086;font-weight:400;font-size:0.85rem;">— ${fmtMoney(g.totalCost)}</span></h3>
    <table style="width:100%;border-collapse:collapse;margin-bottom:10px;">
      ${g.items.map((i) => `
        <tr>
          <td style="padding:6px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(i.title)}</td>
          <td style="padding:6px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(i.assetName || i.locationName || '—')}</td>
          <td style="padding:6px 10px;border-bottom:1px solid #eef0f6;">${escapeHtml(i.deferredReason || '—')}${i.revisitDate ? ` — revisit ${fmtDate(i.revisitDate)}` : ''}</td>
          <td style="padding:6px 10px;border-bottom:1px solid #eef0f6;text-align:right;">${fmtMoney(i.cost)}</td>
        </tr>`).join('')}
    </table>`;
  return htmlShell('Deferred Maintenance Backlog', `${totalCount} deferred finding(s) · ${fmtMoney(totalCost)} total`, `
    ${groups.map(groupHtml).join('') || '<p style="color:#6b7086;">Nothing deferred right now.</p>'}
  `);
}
export function renderDeferredBacklogText({ groups, totalCost, totalCount }) {
  const lines = ['CAMP SYCHAR — DEFERRED MAINTENANCE BACKLOG', `${totalCount} deferred finding(s) — ${fmtMoney(totalCost)} total`, ''];
  groups.forEach((g) => {
    lines.push(`${g.severity} — ${fmtMoney(g.totalCost)}`);
    g.items.forEach((i) => lines.push(`  ${i.title} (${i.assetName || i.locationName || '—'}) — ${fmtMoney(i.cost)}${i.deferredReason ? ` — ${i.deferredReason}` : ''}${i.revisitDate ? `, revisit ${fmtDate(i.revisitDate)}` : ''}`));
  });
  if (!groups.length) lines.push('Nothing deferred right now.');
  return lines.join('\n');
}

// Visitor Activity — two sections so cabin-holder-linked visits read as
// distinct from one-off visitors at a glance, not just via a badge.
export function renderVisitorActivityHtml({ from, to, holders, oneOff, totalVisits, holderVisits, oneOffVisits }) {
  const personHtml = (p) => `
    <div style="border-bottom:1px solid #eef0f6;padding:10px 0;">
      <div><strong>${escapeHtml(p.name)}</strong> <span style="color:#6b7086;font-size:0.85rem;">— ${p.visitCount} visit${p.visitCount === 1 ? '' : 's'}</span></div>
      <div style="color:#6b7086;font-size:0.85rem;">${p.assets.map((a) => `${escapeHtml(a.name)}${a.count > 1 ? ` ×${a.count}` : ''}`).join(' · ')}</div>
      ${p.visits.map((v) => `
        <div style="font-size:0.85rem;margin-top:3px;">${escapeHtml(fmtDate(v.date))}${v.endDate ? `–${escapeHtml(fmtDate(v.endDate))}` : ''}${v.assetName ? ` · ${escapeHtml(v.assetName)}` : ''}${v.purpose ? ` — ${escapeHtml(v.purpose)}` : ''}${p.isCabinHolder && v.visitorName && v.visitorName !== p.name ? ` <span style="color:#6b7086;">(as ${escapeHtml(v.visitorName)})</span>` : ''}</div>`).join('')}
    </div>`;
  const section = (title, list, visits) => `
    <h3 style="margin:20px 0 4px;font-size:1rem;">${escapeHtml(title)} <span style="color:#6b7086;font-weight:400;font-size:0.85rem;">— ${list.length} ${list.length === 1 ? 'person' : 'people'} · ${visits} visit${visits === 1 ? '' : 's'}</span></h3>
    ${list.map(personHtml).join('') || '<p style="color:#6b7086;margin:4px 0;">None in this range.</p>'}`;
  return htmlShell('Visitor Activity', `${from} to ${to} · ${totalVisits} visit(s) · ${holders.length + oneOff.length} people`, `
    ${totalVisits ? `${section('Cabin Holders', holders, holderVisits)}${section('Other Visitors', oneOff, oneOffVisits)}` : '<p style="color:#6b7086;">No visits recorded in this range.</p>'}
  `);
}
export function renderVisitorActivityText({ from, to, holders, oneOff, totalVisits, holderVisits, oneOffVisits }) {
  const lines = ['CAMP SYCHAR — VISITOR ACTIVITY', `${from} to ${to} — ${totalVisits} visit(s), ${holders.length + oneOff.length} people`, ''];
  if (!totalVisits) { lines.push('No visits recorded in this range.'); return lines.join('\n'); }
  const section = (title, list, visits) => {
    lines.push(`${title.toUpperCase()} — ${list.length} people, ${visits} visit(s)`);
    if (!list.length) lines.push('  None in this range.');
    list.forEach((p) => {
      lines.push(`  ${p.name} — ${p.visitCount} visit(s) — ${p.assets.map((a) => `${a.name}${a.count > 1 ? ` x${a.count}` : ''}`).join(', ')}`);
      p.visits.forEach((v) => lines.push(`    ${fmtDate(v.date)}${v.endDate ? `–${fmtDate(v.endDate)}` : ''}${v.assetName ? `  ${v.assetName}` : ''}${v.purpose ? ` — ${v.purpose}` : ''}`));
    });
    lines.push('');
  };
  section('Cabin Holders', holders, holderVisits);
  section('Other Visitors', oneOff, oneOffVisits);
  return lines.join('\n');
}

// Turns a plain-text message (a Requester notification, a free-form message
// from the Requests inbox) into a simple branded HTML body — same htmlShell
// as every other report email, just a preformatted paragraph instead of a
// table. Not for structured reports; those build their own bodyHtml.
export function renderPlainEmailHtml(subject, text) {
  return htmlShell(subject, '', `<div style="white-space:pre-wrap;line-height:1.5;">${escapeHtml(text)}</div>`);
}

// ── Board report rendered from its OWN rows (Build Brief §3/§6/§7) ───────
// The old renderer took a live query, which meant a "published" report re-rendered
// from current data and the freeze was cosmetic. This one renders board_report_items
// and board_report_aggregates, so a report published in March still says in December
// exactly what it said in March.

const SECTION_TITLES = {
  done: 'Work Completed',
  coming_up: 'Coming Up',
  overdue: 'Overdue',
  admin_work: 'Administrative Work',
};

// Figures here describe maintenance and operations tracking. The camp's official books
// live with the treasurer; this is deliberately not accounting, and says so (§7).
const OPS_LABEL = 'Figures reflect maintenance/operations tracking, not the camp\'s official books.';

// ── Summary rich text (Oct 2026 brief, Part 2D) ──────────────────────────
//
// The summary is the only free-form prose on the report, and it needed bullets. Stored as a
// small subset of HTML and sanitised on the way in, because it is rendered into an email that
// goes to the board — anything not on this list is dropped rather than escaped, so a paste
// from Word cannot smuggle styling or script through.
const SUMMARY_ALLOWED_TAGS = new Set(['p', 'br', 'strong', 'b', 'em', 'i', 'ul', 'ol', 'li', 'a']);

// Inline styles, because Gmail strips <style> blocks and Outlook ignores much of what is left.
// Each tag carries its own appearance or it has none.
const SUMMARY_TAG_STYLE = {
  p: 'margin:0 0 10px;',
  ul: 'margin:0 0 10px;padding-left:22px;',
  ol: 'margin:0 0 10px;padding-left:22px;',
  li: 'margin:0 0 4px;',
  a: 'color:#3b5bdb;',
};

export function sanitizeSummaryHtml(raw) {
  if (!raw) return '';
  let html = String(raw);

  // Anything that can execute or load goes first, before the tag walk, so a malformed tag
  // cannot hide one of these inside it.
  html = html.replace(/<\s*(script|style|iframe|object|embed|link|meta)[\s\S]*?<\s*\/\s*\1\s*>/gi, '');
  html = html.replace(/<\s*(script|style|iframe|object|embed|link|meta)\b[^>]*>/gi, '');

  // A rejected <a> has to take its </a> with it, or the text keeps a stray closing tag. The
  // counter pairs them up rather than assuming they are adjacent.
  let droppedAnchors = 0;
  html = html.replace(/<\/?([a-zA-Z0-9]+)([^>]*)>/g, (match, tagRaw, attrs) => {
    const tag = tagRaw.toLowerCase();
    if (!SUMMARY_ALLOWED_TAGS.has(tag)) return '';          // drop the tag, keep its text
    const closing = match.startsWith('</');
    if (closing) {
      if (tag === 'a' && droppedAnchors > 0) { droppedAnchors -= 1; return ''; }
      return `</${tag}>`;
    }
    if (tag === 'a') {
      // Only http(s) and mailto survive, so javascript: and data: cannot ride in on a link.
      const href = (attrs.match(/href\s*=\s*["']([^"']*)["']/i) || [])[1] || '';
      const safe = /^(https?:|mailto:)/i.test(href.trim()) ? href.trim() : null;
      if (!safe) { droppedAnchors += 1; return ''; }
      return `<a href="${safe.replace(/"/g, '&quot;')}" style="${SUMMARY_TAG_STYLE.a}" target="_blank" rel="noopener noreferrer">`;
    }
    const style = SUMMARY_TAG_STYLE[tag];
    return style ? `<${tag} style="${style}">` : `<${tag}>`;
  });

  return html.trim();
}

// An existing plain-text summary still has to read correctly, and Ben's workaround of typing
// "- " at the start of a line becomes the bullets he was imitating (Part 2D). Two spaces or a
// tab before the dash nests one level, which is as deep as the editor goes.
export function plainSummaryToHtml(text) {
  if (!text) return '';
  if (/<(p|ul|ol|li|strong|em|b|i|a)\b/i.test(text)) return sanitizeSummaryHtml(text);  // already rich

  const esc = (t) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const out = [];
  let list = null;          // 'ul' | 'ol' — the outer list, if one is open
  let nested = false;       // is a second-level list open?
  let liOpen = false;       // is an outer <li> still waiting to be closed?

  // A nested list is a CHILD of the item above it, not its sibling. That means the outer <li>
  // stays open until the nested list has been written and closed — writing </li> eagerly
  // produced <ul><li>..</li><ul>..</ul></ul>, which is invalid and which Outlook renders flat.
  const closeNested = () => { if (nested) { out.push('</ul>'); nested = false; } };
  const closeLi = () => { closeNested(); if (liOpen) { out.push('</li>'); liOpen = false; } };
  const closeList = () => { closeLi(); if (list) { out.push(`</${list}>`); list = null; } };

  for (const rawLine of String(text).split(/\r?\n/)) {
    const line = rawLine.replace(/\s+$/, '');
    if (!line.trim()) { closeList(); continue; }

    const bullet = line.match(/^(\s*)[-*•]\s+(.*)$/);
    const numbered = line.match(/^(\s*)\d+[.)]\s+(.*)$/);
    const m = bullet || numbered;
    if (m) {
      const want = bullet ? 'ul' : 'ol';
      const indented = m[1].length >= 2;
      if (indented) {
        if (!list) { out.push(`<${want} style="${SUMMARY_TAG_STYLE[want]}">`); list = want; }
        if (!liOpen) { out.push(`<li style="${SUMMARY_TAG_STYLE.li}">`); liOpen = true; }
        if (!nested) { out.push(`<ul style="${SUMMARY_TAG_STYLE.ul}">`); nested = true; }
        out.push(`<li style="${SUMMARY_TAG_STYLE.li}">${esc(m[2])}</li>`);
      } else {
        closeLi();
        if (list !== want) { closeList(); out.push(`<${want} style="${SUMMARY_TAG_STYLE[want]}">`); list = want; }
        out.push(`<li style="${SUMMARY_TAG_STYLE.li}">${esc(m[2])}`);
        liOpen = true;
      }
      continue;
    }
    closeList();
    out.push(`<p style="${SUMMARY_TAG_STYLE.p}">${esc(line)}</p>`);
  }
  closeList();
  return out.join('');
}

// For the plain-text half of the email, and anywhere a summary needs to be read without markup.
export function summaryHtmlToText(html) {
  if (!html) return '';
  return String(html)
    .replace(/<\/(p|div|li|ul|ol)>/gi, '\n')
    .replace(/<li[^>]*>/gi, '  - ')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function moneyHeaderHtml(aggregates) {
  const byGroup = (g) => aggregates.filter((a) => a.GroupKey === g);
  const money = byGroup('money');
  const savings = byGroup('savings');
  if (!money.length && !savings.length) return '';
  const cell = (a) => `
    <td style="padding:8px 14px;border-right:1px solid #eef0f6;">
      <div style="color:#6b7086;font-size:0.78rem;text-transform:uppercase;">${escapeHtml(a.Label)}</div>
      <div style="font-size:1.05rem;font-weight:700;">${a.ValueNumeric != null ? fmtMoney(a.ValueNumeric) : escapeHtml(a.ValueText || '—')}</div>
    </td>`;
  // Both rows must have the same number of cells or Outlook renders a ragged table — it does
  // not reflow a short row the way a browser does. The shorter row gets an empty filler cell.
  const cols = Math.max(money.length, savings.length, 1);
  const row = (cells) => {
    if (!cells.length) return '';
    const filler = '<td style="padding:8px 14px;"></td>'.repeat(cols - cells.length);
    return `<tr>${cells.map(cell).join('')}${filler}</tr>`;
  };
  return `
    <table role="presentation" style="width:100%;border-collapse:collapse;background:#f9fafc;border:1px solid #eef0f6;border-radius:10px;margin-bottom:18px;table-layout:fixed;">
      ${row(money)}
      ${row(savings)}
    </table>`;
}

// Photos under a report item (Part 2C).
//
// Grouped by the item, ordered before → during → after, and when an item has both a before and
// an after they go SIDE BY SIDE — before left, after right — stacking on a narrow screen. No
// attempt is made to pair particular shots: the brief says group by work order and order by
// stage, which is what a reader needs to follow.
//
// Laid out with a table and width percentages rather than flex or grid, because Outlook's
// rendering engine is Word and supports neither.
function photoFigureHtml(photo, { half = false } = {}) {
  const label = photo.SnapLabel || photo.Label || '';
  const width = half ? '100%' : '100%';
  return `
    <td style="width:${half ? '50%' : '100%'};padding:0 6px 10px;vertical-align:top;">
      <img src="cid:${escapeHtml(photo.Cid)}" alt="${escapeHtml(label)}"
           width="100%" style="width:${width};max-width:100%;height:auto;display:block;border-radius:8px;border:1px solid #e5e7f0;" />
      ${label ? `<div style="color:#6b7086;font-size:0.8rem;margin-top:4px;line-height:1.3;">${escapeHtml(label)}</div>` : ''}
    </td>`;
}

function itemPhotosHtml(photos) {
  if (!photos || !photos.length) return '';
  const rows = [];
  // A before and an after sit together; anything else runs full width.
  const before = photos.filter((p) => p.StageOrder === 1);
  const after = photos.filter((p) => p.StageOrder === 3);
  const rest = photos.filter((p) => p.StageOrder !== 1 && p.StageOrder !== 3);
  const pairs = Math.min(before.length, after.length);
  for (let i = 0; i < pairs; i++) {
    rows.push(`<tr>${photoFigureHtml(before[i], { half: true })}${photoFigureHtml(after[i], { half: true })}</tr>`);
  }
  for (const p of [...before.slice(pairs), ...rest, ...after.slice(pairs)]) {
    rows.push(`<tr>${photoFigureHtml(p)}</tr>`);
  }
  return `
    <table role="presentation" width="100%" style="width:100%;border-collapse:collapse;margin:8px 0 4px;">
      ${rows.join('')}
    </table>`;
}

function itemLineHtml(it) {
  // Dates read as a span rather than a single stamp (decisions §7): when something started
  // and whether it has finished is more use to a board than one undated figure.
  const dates = it.SnapStartDate
    ? `Started ${fmtDate(it.SnapStartDate)} · ${it.SnapDate ? `Completed ${fmtDate(it.SnapDate)}` : 'In progress'}`
    : (it.SnapDate ? fmtDate(it.SnapDate) : null);
  // Money: actual only, and only when there is one. An estimate is labelled "est." and shown
  // on open work alongside it — never instead of it and never summed (decisions §2, §3).
  const money = it.SnapCost != null ? fmtMoney(it.SnapCost) : null;
  const est = it.SnapEstCost != null && !it.SnapDate ? `~${fmtMoney(it.SnapEstCost)} est.` : null;
  const bits = [
    it.SnapAssetName, it.SnapStatus, dates,
    it.SnapHours != null ? fmtHours(it.SnapHours) : null,
    money, est,
  ].filter(Boolean);
  // "Camp $1,000 · Personal $240" — who actually paid, from the receipts allocated to the work.
  const funding = Array.isArray(it.SnapFunding) && it.SnapFunding.length
    ? it.SnapFunding.map((f) => `${f.Source} ${fmtMoney(f.Amount)}`).join(' · ')
    : null;
  // The em-dash suffix is for things the detail line does not already say. Printing the
  // asset there as well gave "Front Gate Repair — Red Gate" above "Red Gate · Done · …",
  // and an admin task's category turned into "Fixed NVR Hard Drive — Other", which is noise
  // to a board reader (fix 8).
  // An admin task's subtitle only ever carried its category, which is internal filing rather
  // than something the board needs, so it is not printed at all. Existing snapshot rows still
  // hold it — the upsert's COALESCE cannot clear a stored value — so the guard lives here as
  // well as at the source.
  const suffix = it.SnapSubtitle
    && it.SnapSubtitle !== it.SnapAssetName
    && it.ItemType !== 'admin_task'
    ? it.SnapSubtitle : null;
  return `
    <div style="border-bottom:1px solid #eef0f6;padding:9px 0;">
      <div><strong>${escapeHtml(it.SnapTitle || '(untitled)')}</strong>${suffix ? ` <span style="color:#6b7086;">— ${escapeHtml(suffix)}</span>` : ''}</div>
      ${bits.length ? `<div style="color:#6b7086;font-size:0.85rem;">${escapeHtml(bits.join(' · '))}</div>` : ''}
      ${funding ? `<div style="color:#6b7086;font-size:0.85rem;">Funded by ${escapeHtml(funding)}</div>` : ''}
      ${it.SnapProgress ? `<div style="color:#6b7086;font-size:0.85rem;">${escapeHtml(it.SnapProgress)}</div>` : ''}
      ${itemPhotosHtml(it.Photos)}
      ${it.ReportNote ? `<div style="margin-top:4px;font-size:0.9rem;">${escapeHtml(it.ReportNote)}</div>` : ''}
    </div>`;
}

// A summary work order prints one line and swallows its job lines; an itemized one
// prints its lines instead. Summary is the default for every WO (§6).
function sectionHtml(section, items) {
  if (!items.some((i) => i.Section === section && i.Included)) return '';
  // One rule, shared with the footer, so a section subtotal and the grand total can never
  // disagree about what counts again.
  const visible = visibleItems(items).filter((i) => i.Section === section);
  if (!visible.length) return '';
  const hours = visible.reduce((t, i) => t + (i.SnapHours || 0), 0);
  const cost = visible.reduce((t, i) => t + (i.SnapCost || 0), 0);
  const sub = [hours ? fmtHours(hours) : null, cost ? fmtMoney(cost) : null].filter(Boolean).join(' · ');
  return `
    <h2 style="margin:26px 0 4px;font-size:1.1rem;border-top:2px solid #eef0f6;padding-top:14px;">
      ${escapeHtml(SECTION_TITLES[section] || section)}
      <span style="color:#6b7086;font-weight:400;font-size:0.85rem;"> — ${visible.length} item(s)${sub ? ` · ${sub}` : ''}</span>
    </h2>
    ${visible.map(itemLineHtml).join('')}`;
}

// What the reader can actually see: included, minus the job lines their work order is
// summarising away. sectionHtml() has always applied this to its own subtotals; the grand
// footer did not, so it counted and totalled 15 rows nobody could see.
function visibleItems(items) {
  const summaryWoIds = new Set(
    items.filter((i) => i.Included && i.ItemType === 'work_order' && i.DisplayMode === 'summary')
      .map((i) => i.ItemId)
  );
  return items.filter((i) => i.Included
    && !(i.ItemType === 'job_line' && summaryWoIds.has(i.ParentWorkOrderId)));
}

export function renderBoardReportItemsHtml({ report, items, aggregates, reportPhotos = [] }) {
  const sections = ['done', 'coming_up', 'overdue', 'admin_work'];
  const visible = visibleItems(items);
  const grandHours = visible.reduce((t, i) => t + (i.SnapHours || 0), 0);
  const grandCost = visible.reduce((t, i) => t + (i.SnapCost || 0), 0);
  return htmlShell(
    `Board Report — ${report.Title}`,
    `${report.PeriodStart} to ${report.PeriodEnd} · looking ahead to ${report.ForwardEnd}${report.Status === 'draft' ? ' · DRAFT' : ''}`,
    `
    ${moneyHeaderHtml(aggregates)}
    ${report.SummaryNotes ? `<div style="background:#fbfbfe;border:1px solid #eef0f6;border-radius:10px;padding:14px;margin-bottom:6px;">${plainSummaryToHtml(report.SummaryNotes)}</div>` : ''}
    ${sections.map((sec) => sectionHtml(sec, items)).join('')}
    ${Array.isArray(reportPhotos) && reportPhotos.length ? `
      <h2 style="margin:26px 0 4px;font-size:1.1rem;border-top:2px solid #eef0f6;padding-top:14px;">Other photos this month</h2>
      ${itemPhotosHtml(reportPhotos)}` : ''}
    <div style="margin-top:22px;padding-top:12px;border-top:2px solid #eef0f6;font-weight:700;">
      Total — ${visible.length} item(s)${grandHours ? ` · ${fmtHours(grandHours)}` : ''}${grandCost ? ` · ${fmtMoney(grandCost)} recorded cost of work shown` : ''}
    </div>
    ${grandCost ? `<div style="margin-top:5px;color:#6b7086;font-size:0.8rem;line-height:1.4;">
      Recorded cost is what the work cost, whoever paid for it — it is <strong>not</strong> camp
      spend. Who funded what is set out above. Estimates on open items are shown for context and
      are never added into this total.
    </div>` : ''}
    <div style="margin-top:8px;color:#9298b0;font-size:0.78rem;">${escapeHtml(OPS_LABEL)}</div>
  `
  );
}

export function renderBoardReportItemsText({ report, items, aggregates }) {
  const lines = [`CAMP SYCHAR — BOARD REPORT — ${report.Title}`,
    `${report.PeriodStart} to ${report.PeriodEnd} (ahead to ${report.ForwardEnd})${report.Status === 'draft' ? ' — DRAFT' : ''}`, ''];
  for (const a of aggregates.filter((x) => ['money', 'savings'].includes(x.GroupKey))) {
    lines.push(`${a.Label}: ${a.ValueNumeric != null ? fmtMoney(a.ValueNumeric) : (a.ValueText || '—')}`);
  }
  if (report.SummaryNotes) lines.push('', summaryHtmlToText(report.SummaryNotes));
  const visible = visibleItems(items);
  for (const sec of ['done', 'coming_up', 'overdue', 'admin_work']) {
    const rows = visible.filter((i) => i.Section === sec);
    if (!rows.length) continue;
    lines.push('', `${(SECTION_TITLES[sec] || sec).toUpperCase()} (${rows.length}):`);
    for (const it of rows) {
      const bits = [it.SnapAssetName, it.SnapDate ? fmtDate(it.SnapDate) : null,
        it.SnapCost != null ? fmtMoney(it.SnapCost) : null].filter(Boolean);
      lines.push(`  ${it.SnapTitle || '(untitled)'}${bits.length ? ` — ${bits.join(' · ')}` : ''}`);
      if (it.ReportNote) lines.push(`      ${it.ReportNote}`);
    }
  }
  const grandCost = visible.reduce((t, i) => t + (i.SnapCost || 0), 0);
  const grandHours = visible.reduce((t, i) => t + (i.SnapHours || 0), 0);
  lines.push('', `TOTAL — ${visible.length} item(s)`
    + `${grandHours ? ` · ${fmtHours(grandHours)}` : ''}`
    + `${grandCost ? ` · ${fmtMoney(grandCost)} recorded cost of work shown` : ''}`);
  if (grandCost) {
    lines.push('Recorded cost is what the work cost, whoever paid for it — it is NOT camp spend.',
      'Who funded what is set out above. Estimates on open items are never added into this total.');
  }
  lines.push('', OPS_LABEL);
  return lines.join('\n');
}
